version: '3'

services:

  nginx:
    container_name: nginx
    image: chaiyd/nginx:1.20.1
    restart: always
    volumes:
      - ./data/logs:/etc/nginx/logs
      - ./data/conf.d:/etc/nginx/conf.d
      
    ports:
      - "80:80"
      - "443:443"
    #environment:
    #  - NGINX_PORT=80
    user: root
