version: '2'

services:

  nginx:
    container_name: nginx
    image: chaiyd-nginx:v0.1
    restart: always
    volumes:
      - /data/docker/nginx:/etc/nginx/logs
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
    user: root
